#!/bin/sh

set -e

#mirror_url="https://www.nic.funet.fi/debian/"

#case "$(dpkg --print-architecture)" in
#	amd64)
#		_SOURCE="true"
#		;;
#
#	i386)
#		_SOURCE="false"
#		;;
#esac

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--distribution bookworm \
	--archive-areas "main contrib non-free non-free-firmware" \
	--debian-installer live \
	--linux-packages "linux-image linux-headers" \
#	--source "${_SOURCE}" \

"${@}"
